name = "comprehendo"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Static assets configuration
[assets]
directory = ".open-next/assets"

[[d1_databases]]
binding = "DB"
database_name = "comprehendo-db"
database_id = "a3e39277-f1f5-4c99-bee5-b41a20e01afa"
migrations_dir = "migrations"

[vars]
NODE_ENV = "production"

